---
DataSetName: "small_test"

Paths:
  Reads: test_data
  AlignPath: resources/mnv_genomes_181120/Mod_CR6

Data:
  RefGenomeName: "CR6" # currently, only options are CR6 or CW3
  RefGenome: resources/mnv_genomes_181120/Modified_CR6.fas
  Adapters: resources/contaminants_181120/Baldridge_nextera.fa

Patterns:
  Read1Identifiers: ["_R1"]
  Read2Identifiers: ["_R2"]
  ReadExtensions: [".fastq.gz"]

Tools:
  bbtools: eval $( spack load --sh bbmap@38.63 )
  samtools: eval $( spack load --sh samtools@1.15.1 )
  bowtie2: eval $( /ref/lhlab/software/spack-0.19.2/bin/spack load --sh bowtie2@2.4.2 )
  bcftools: 
  bedtools: eval $( /ref/lhlab/software/spack-0.19.2/bin/spack load --sh bedtools2@2.30.0 )
  lofreq: eval "$(conda shell.bash hook)"; conda activate lofreq_2.1.5
  R: eval $( spack load --sh r@4.2.2 )
 
System:
  JavaMem: -Xmx48g
